apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ns-devith
spec:
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - |
          i=0
          while true; do
            echo "$(date) hello from ns-devith line $i"
            echo "$(date) hello from ns-devith line $i" >> /data/file.txt
            i=$((i+1))
            sleep 2
          done
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-data