apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ns-devith
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo hello > /data/file.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: my-data